### ISSUE TITLE
rapicorn 17.0.0 not building on fedora 27

### ISSUE THREAD

**Issue by ngeiswei** [tim-janik/rapicorn#14]
I tried to compile rapicorn 17.0.0 under fedora 27 but got the following error:
```
cd ~/Sources/rapicorn-17.0.0/; make
Making all in po
make[1]: Entering directory '/home/nilg/Sources/rapicorn-17.0.0/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/nilg/Sources/rapicorn-17.0.0/po'
Making all in .
make[1]: Entering directory '/home/nilg/Sources/rapicorn-17.0.0'
  GEN      cython/Rapicorn.cc

Error compiling Cython file:
------------------------------------------------------------
...
    cdef const char* __Pyx_PyObject_AsStringAndSize(object, Py_ssize_t*) except NULL

@cname("__pyx_convert_string_from_py_std__in_string")
cdef string __pyx_convert_string_from_py_std__in_string(object o) except *:
    cdef Py_ssize_t length
    cdef const char* data = __Pyx_PyObject_AsStringAndSize(o, &length)
                                                              ^
------------------------------------------------------------

string.from_py:15:63: local variable 'length' might be referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/cython", line 11, in <module>
    load_entry_point('Cython==0.27.3', 'console_scripts', 'cython')()
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 703, in setuptools_main
    return main(command_line = 1)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 720, in main
    result = compile(sources, options)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 695, in compile
    return compile_multiple(source, options)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 673, in compile_multiple
    result = run_pipeline(source, options, context=context)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Main.py", line 494, in run_pipeline
    err, enddata = Pipeline.run_pipeline(pipeline, source)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 354, in run_pipeline
    data = run(phase, data)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 334, in run
    return phase(data)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/Pipeline.py", line 129, in inject_utility_code_stage
    tree = utilcode.get_tree(cython_scope=context.cython_scope)
  File "/usr/lib64/python2.7/site-packages/Cython/Compiler/UtilityCode.py", line 186, in get_tree
    assert not err, err
AssertionError: Abort error: fatal errors
make[1]: *** [Makefile:3933: cython/Rapicorn.cc] Error 1
make[1]: Leaving directory '/home/nilg/Sources/rapicorn-17.0.0'
make: *** [Makefile:3412: all-recursive] Error 1
```
I wish I could help but I'm not familiar with cython.

**Comment by ngeiswei** [comment]
I cloned the repo, ran `./autogen.sh` but I'm getting another error:
```
[nilg@laptop rapicorn]$ ./autogen.sh 
+ rm -rf autom4te.cache/ ./config.cache ./config.status
+ false
+ aclocal --force
+ libtoolize --force --install
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'config'.
libtoolize: linking file 'config/config.guess'
libtoolize: linking file 'config/config.sub'
libtoolize: linking file 'config/install-sh'
libtoolize: linking file 'config/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'config'.
libtoolize: linking file 'config/libtool.m4'
libtoolize: linking file 'config/ltoptions.m4'
libtoolize: linking file 'config/ltsugar.m4'
libtoolize: linking file 'config/ltversion.m4'
libtoolize: linking file 'config/lt~obsolete.m4'
libtoolize: Consider adding '-I config' to ACLOCAL_AMFLAGS in Makefile.am.
+ autoconf --force
configure.ac:336: error: possibly undefined macro: AC_PYTHON_DEVEL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```
hmm, both points to a python/cython problem...

**Comment by ngeiswei** [comment]
I solved the `possibly undefined macro: AC_PYTHON_DEVEL` error by installing `autoconf-archive`, however I get the same problem as with the tarball.

**Comment by ngeiswei** [comment]
It appears this error only occurs with cython 0.26.1 and on. So a workaround is to install a previous version like 0.26 https://github.com/cython/cython/releases/tag/0.26

**Comment by ngeiswei** [comment]
Now I'm having this error
```
./rcore/cxxaux.hh:447:82: error: request for member ‘__accept_accessor__<Rapicorn::ToXmlVisitor>’ in ‘std::declval<bool>()’, which is of non-class type ‘bool’
 struct Has__accept_accessor__<T, V, void_t< decltype (std::declval<T>().template __accept_accessor__<V> (*(V*) NULL)) >> : std::true_type {};
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
```
It almost look like gcc bug though... EDIT: my version of gcc is 8.1.1

**Comment by ngeiswei** [comment]
Yep, I installed gcc 7.3 and now it compiles, the only problem is that the it crashes when I launch it
```
/usr/local/lib/beast-0-11/bin/beast-0.11.1: ../aidacc/aida.cc:2691: client_orb_object_deleting: GCStats: ClientConnectionImpl: SEEN_GARBAGE (0000000000000001)
/usr/local/lib/beast-0-11/bin/beast-0.11.1: ../aidacc/aida.cc:3054: start_garbage_collection: GCStats: ServerConnectionImpl: GARBAGE_SWEEP: 1 candidates
/usr/local/lib/beast-0-11/bin/beast-0.11.1: ../aidacc/aida.cc:2784: gc_sweep: GCStats: ClientConnectionImpl: GARBAGE_REPORT: 1 trash ids
/usr/local/lib/beast-0-11/bin/beast-0.11.1: ../aidacc/aida.cc:3181: dispatch: GCStats: ServerConnectionImpl: GARBAGE_COLLECTED: considered=1 retained=0 purged=1 active=1
Segmentation fault (core dumped)
```

**Comment by tim-janik** [comment]
Please note that there is now a 0.12.0 release of Beast which doesn't require librapicorn. So there's no need to keep trying to build rapicorn.

**Comment by ngeiswei** [comment]
Ah, it would be good if https://github.com/tim-janik/beast#requirements would reflect that.
